# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/_Projects/UniverseLogistician

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/_Projects/UniverseLogistician

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/_Projects/UniverseLogistician/CMakeFiles /mnt/d/_Projects/UniverseLogistician//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/_Projects/UniverseLogistician/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named util

# Build rule for target.
util: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 util
.PHONY : util

# fast build rule for target.
util/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/build
.PHONY : util/fast

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

#=============================================================================
# Target rules for targets named UL_Server

# Build rule for target.
UL_Server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UL_Server
.PHONY : UL_Server

# fast build rule for target.
UL_Server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UL_Server.dir/build.make CMakeFiles/UL_Server.dir/build
.PHONY : UL_Server/fast

#=============================================================================
# Target rules for targets named UL_Client

# Build rule for target.
UL_Client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UL_Client
.PHONY : UL_Client

# fast build rule for target.
UL_Client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UL_Client.dir/build.make CMakeFiles/UL_Client.dir/build
.PHONY : UL_Client/fast

apps/client.o: apps/client.cpp.o
.PHONY : apps/client.o

# target to build an object file
apps/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UL_Client.dir/build.make CMakeFiles/UL_Client.dir/apps/client.cpp.o
.PHONY : apps/client.cpp.o

apps/client.i: apps/client.cpp.i
.PHONY : apps/client.i

# target to preprocess a source file
apps/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UL_Client.dir/build.make CMakeFiles/UL_Client.dir/apps/client.cpp.i
.PHONY : apps/client.cpp.i

apps/client.s: apps/client.cpp.s
.PHONY : apps/client.s

# target to generate assembly for a file
apps/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UL_Client.dir/build.make CMakeFiles/UL_Client.dir/apps/client.cpp.s
.PHONY : apps/client.cpp.s

apps/server.o: apps/server.cpp.o
.PHONY : apps/server.o

# target to build an object file
apps/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UL_Server.dir/build.make CMakeFiles/UL_Server.dir/apps/server.cpp.o
.PHONY : apps/server.cpp.o

apps/server.i: apps/server.cpp.i
.PHONY : apps/server.i

# target to preprocess a source file
apps/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UL_Server.dir/build.make CMakeFiles/UL_Server.dir/apps/server.cpp.i
.PHONY : apps/server.cpp.i

apps/server.s: apps/server.cpp.s
.PHONY : apps/server.s

# target to generate assembly for a file
apps/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UL_Server.dir/build.make CMakeFiles/UL_Server.dir/apps/server.cpp.s
.PHONY : apps/server.cpp.s

src/game.o: src/game.cpp.o
.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i
.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s
.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/util.o: src/util.cpp.o
.PHONY : src/util.o

# target to build an object file
src/util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/src/util.cpp.o
.PHONY : src/util.cpp.o

src/util.i: src/util.cpp.i
.PHONY : src/util.i

# target to preprocess a source file
src/util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/src/util.cpp.i
.PHONY : src/util.cpp.i

src/util.s: src/util.cpp.s
.PHONY : src/util.s

# target to generate assembly for a file
src/util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/src/util.cpp.s
.PHONY : src/util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... UL_Client"
	@echo "... UL_Server"
	@echo "... game"
	@echo "... util"
	@echo "... apps/client.o"
	@echo "... apps/client.i"
	@echo "... apps/client.s"
	@echo "... apps/server.o"
	@echo "... apps/server.i"
	@echo "... apps/server.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

